---
title: "IMDB Datasets"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

### IMDB Datasets
https://www.imdb.com/interfaces/
https://datasets.imdbws.com/

```{r setup}
library(data.table)
library(ggplot2)
library(ggthemes)
library(scales)
```

```{r shortcutLoadIMDbData}
movieratings = fread("~/Downloads/imdb.movieratings.csv.gz")

##
## Dont execute next block if you read file here
## 
```


```{r loadIMDbData}
#basics = fread("~/Downloads/title.basics.tsv.gz", na.strings = "\\N")
basics = fread("https://datasets.imdbws.com/title.basics.tsv.gz")
#ratings = fread("~/Downloads/title.ratings.tsv.gz", na.strings = "\\N")
ratings = fread("https://datasets.imdbws.com/title.ratings.tsv.gz")
#episodes = fread("~/Downloads/title.episode.tsv.gz", na.strings = "\\N")
episodes = fread("https://datasets.imdbws.com/title.episode.tsv.gz")
setkey(ratings, "tconst")

# parse genres by order and then pick primary genre and type for each title
basics[, c("genre1", "genre2", "genre3") := tstrsplit(genres, ",", fixed=TRUE)]
GENRES = c("Comedy", "Drama", "Action", "Crime", "Adventure", "Horror", "Biography", "Family", "Western", "Thriller", "Romance", "Fantasy", "Sport", "Sci-Fi", "Mystery", "Musical", "History", "War", "Film-Noir")
TYPES = c("Documentary", "Animation", "Reality-TV", "Short", "Music", "Adult", "Game-Show", "Talk-Show", "News")
basics[, c("mainGenre", "mainType") := list(
  ifelse(genre1 %in% GENRES, genre1, 
         ifelse(genre2 %in% GENRES, genre2, 
                ifelse(genre3 %in% GENRES, genre3, NA))),
  ifelse(genre1 %in% TYPES, genre1, 
         ifelse(genre2 %in% TYPES, genre2, 
                ifelse(genre3 %in% TYPES, genre3, "Film")))
)]

# parse genres by type
basics[, c('genresCount',
           'isGenreAction', 'isGenreAdult', 'isGenreAdventure', 'isGenreAnimation', 
           'isGenreBiography', 'isGenreComedy', 'isGenreCrime', 'isGenreDocumentary', 'isGenreDrama',
           'isGenreFamily', 'isGenreFantasy', 'isGenreFilmNoir', 'isGenreGameShow',
           'isGenreHistory', 'isGenreHorror', 'isGenreMusic', 'isGenreMusical', 'isGenreMystery',
           'isGenreNews', 'isGenreRealityTV', 'isGenreRomance', 'isGenreSciFi', 'Short',
           'isGenreSport', 'isGenreTalkShow', 'isGenreThriller', 'isGenreWar',
           'isGenreWestern') := 
         list(nchar(genres) - nchar(gsub(",", "", genres)) + 1,
              grepl("Action", genres), grepl("Adult", genres), grepl("Adventure", genres), grepl("Animation", genres),
              grepl("Biography", genres), grepl("Comedy", genres), grepl("Crime", genres), grepl("Documentary", genres), grepl("Drama", genres),
              grepl("Family", genres), grepl("Fantasy", genres), grepl("Film-Noir", genres), grepl("Game-Show", genres),
              grepl("History", genres), grepl("Horror", genres), grepl("Music", genres), grepl("Musical", genres), grepl("Mystery", genres),
              grepl("News", genres), grepl("Reality-TV", genres), grepl("Romance", genres), grepl("Sci-Fi", genres), grepl("Short", genres),
              grepl("Sport", genres), grepl("Talk-Show", genres), grepl("Thriller", genres), grepl("War", genres),
              grepl("Western", genres))]
movieratings = ratings[basics][!is.na(averageRating)]
movieratings[, titleType2 := ifelse(titleType %in% c('movie', 'tvMovie'), 'movie',
                                   ifelse(titleType %in% c('tvMiniSeries', 'tvSeries'), 'series', titleType))]
movieratings[runtimeMinutes=='\\N', runtimeMinutes := NA]
movieratings[, runtimeMinutes := as.integer(runtimeMinutes)]

episoderatings = ratings[episodes][!is.na(averageRating)]
titleepisoderatings = episoderatings[movieratings, on=c(parentTconst = "tconst")]
setnames(titleepisoderatings, 
         c("tconst", "i.averageRating", "i.numVotes"), 
         c("tconstEpisode", "titleAverageRating", "titleNumVotes"))

fwrite(movieratings, "~/Downloads/imdb.movieratings.csv.gz")
```

```{r subtitleFun}
makeSubtitle <- function(m, data) {
  tt = table(data$titleType)
  subtitle = sprintf("Titles with %d+ votes: %d movies, %d TV movies, %d TV mini-series, and %d TV series", 
                   m, tt['movie'], tt['tvMovie'], tt['tvMiniSeries'], tt['tvSeries'])
  return(subtitle)
}
```

### Ratings

```{r distributionsRatings, fig.width=7, fig.height=8}
imdb_title = "IMDb Rating Distributions by Title Types"
data = movieratings[titleType %in% c("movie", "tvSeries", "tvMovie", "tvMiniSeries")]
data[, titleType :=
       factor(titleType, levels = c("movie", "tvMovie", "tvMiniSeries", "tvSeries"), 
         ordered = TRUE)]

genre_map = c("FALSE"="Fiction", "TRUE"="Documentary")
title_map = c(movie="Movie", tvMiniSeries="TV Mini Series", tvMovie="TV Movie", tvSeries="TV Series")
ggplot(data) +
  geom_histogram(aes(x=averageRating, fill=titleType), bins=91) +
  scale_x_continuous(breaks = c(1,5,6,7,8,9,10)) +
  facet_grid(titleType ~ isGenreDocumentary, scales = "free_y",
             labeller = labeller(titleType = title_map, isGenreDocumentary = genre_map)) +
  labs(title = imdb_title, subtitle = makeSubtitle(0, data), x="rating", y=NULL,
       caption = "Source: https://www.imdb.com/interfaces/") +
  theme_pander(base_size = 12, base_family = "Courier") +
  theme(plot.margin = margin(10, 10, 10, 10),
        legend.position = "none",
        plot.title = element_text(family = "Palatino", size=16))
```


```{r distributionsNumVotes, fig.width=7, fig.height=8}
imdb_title = "IMDb Number of Votes Distributions by Title Types"
ggplot(data[numVotes < 1000]) +
  geom_histogram(aes(x=numVotes, fill=titleType), bins=100) +
  scale_x_continuous(breaks = c(1, 250, 500, 750)) +
  facet_grid(titleType ~ isGenreDocumentary, scales = "free_y",
             labeller = labeller(titleType = title_map, isGenreDocumentary = genre_map)) +
  labs(title = imdb_title, subtitle = makeSubtitle(500, data[numVotes < 500]), x="votes", y=NULL) +
  theme_few(base_family = 'Palatino', base_size = 12) +
  theme(legend.position = 'none')
```

```{r fictionMoviesAndSeriesData}
# 25,000 is minimum number of votes to be considered for the IMDb Top Rated 250 titles.
m = as.integer(25000/25)
data = movieratings[titleType2 %in% c("movie", "series") & numVotes > m & !isGenreDocumentary]

moviePercentiles = quantile(data[titleType=='movie']$averageRating, probs=c(0.25, 0.5, 0.75, 0.9, 0.95, 0.99))
tvMiniSeriesPercentiles = quantile(data[titleType=='tvMiniSeries']$averageRating, probs=c(0.25, 0.5, 0.75, 0.9, 0.95, 0.99))
tvMoviePercentiles = quantile(data[titleType=='tvMovie']$averageRating, probs=c(0.25, 0.5, 0.75, 0.9, 0.95, 0.99))
tvSeriesPercentiles = quantile(data[titleType=='tvSeries']$averageRating, probs=c(0.25, 0.5, 0.75, 0.9, 0.95, 0.99))

# goodBadUglySlope = rbind(data.table(type=rep("Movie", length(moviePercentiles)),
#                                rank=names(moviePercentiles), rating=moviePercentiles),
#                     data.table(type=rep("TV Mini Series", length(tvMiniSeriesPercentiles)),
#                                rank=names(tvMiniSeriesPercentiles), rating=tvMiniSeriesPercentiles),
#                     data.table(type=rep("TV Movie", length(tvMoviePercentiles)),
#                                rank=names(tvMoviePercentiles), rating=tvMoviePercentiles),
#                     data.table(type=rep("TV Series", length(tvSeriesPercentiles)),
#                                rank=names(tvSeriesPercentiles), rating=tvSeriesPercentiles))
# goodBadUglySlope[, c("rank", "type") := list(
#   factor(rank, labels = c("Bad\n25%", "Average\n50%", "Good\n75%",
#                           "Very Good\n90%", "Excellent\n95%", "Very Best\n99%")),
#   factor(type, labels = c("Movie", "TV Mini Series", "TV Movie", "TV Series"), ordered = TRUE))]
```


```{r barplotRatingByTypeDodge, fig.width=6, fig.height=4.5}
goodBadUgly = rbind(data.table(type=rep("Movie", length(moviePercentiles)),
                               rank=names(moviePercentiles), rating=moviePercentiles),
                    data.table(type=rep("TV Mini Series", length(tvMiniSeriesPercentiles)),
                               rank=names(tvMiniSeriesPercentiles), rating=tvMiniSeriesPercentiles),
                    data.table(type=rep("TV Movie", length(tvMoviePercentiles)),
                               rank=names(tvMoviePercentiles), rating=tvMoviePercentiles),
                    data.table(type=rep("TV Series", length(tvSeriesPercentiles)),
                               rank=names(tvSeriesPercentiles), rating=tvSeriesPercentiles))

goodBadUgly[, c("rank", "type") := list(
  factor(rank, # levels = c("25%", "50%", "75%", "90%", "95%", "99%"), 
         labels = c("Bad\n25%", "Average\n50%", "Good\n75%", 
                    "Very Good\n90%", "Excellent\n95%", "Very Best\n99%"),
         #labels = c("Bad (25%)", "Average (50%)", "Good (75%)",
         #           "Very Good (90%)", "Excellent (95%)", "Very Best (99%)"), 
         ordered = TRUE),
  factor(type, levels = c("Movie", "TV Movie", "TV Mini Series", "TV Series"),
         ordered = TRUE))]

imdb_title = "IMDb Rating Percentiles by Title Types"
ggplot(goodBadUgly) +
  geom_bar(aes(rank, rating, group=type, fill=type), color="black", position = "dodge", stat = "identity") +
  scale_y_continuous(breaks = seq(5,10), sec.axis = dup_axis()) +
  scale_fill_tableau(guide = guide_legend(nrow = 1, byrow = TRUE), name = NULL) +
  # coord_flip() +
  labs(title=imdb_title,
    subtitle = makeSubtitle(m, data),
    caption = "Source: https://www.imdb.com/interfaces/",x=NULL, y=NULL) +
  theme_pander(base_size = 16, base_family = "Courier") +
  theme(plot.margin = margin(10, 10, 10, 10),
        legend.position = "bottom",
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        plot.title = element_text(family = "Palatino", size=16))
```


```{r barplotRatingByTypeStack, fig.width=6, fig.height=4.5}
goodBadUgly[order(rating), ratingDelta := rating - shift(rating, 1, fill=0), by=type]
setorder(goodBadUgly, type, -rating)

ggplot(goodBadUgly) +
  geom_bar(aes(type, rating, fill=rank), color="black", position = "identity", stat = "identity", alpha = 1) +
  scale_y_continuous(breaks = seq(5,10), sec.axis = dup_axis()) +
  scale_fill_few(guide = guide_legend(nrow = 1, byrow = TRUE), name = NULL) +
  # coord_flip() +
  labs(title=imdb_title,
    subtitle = makeSubtitle(m, data),
    caption = "Source: https://www.imdb.com/interfaces/",x=NULL, y=NULL) +
  theme_pander(base_size = 16, base_family = "Courier") +
  theme(plot.margin = margin(10, 10, 10, 10),
        legend.position = "bottom",
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank(),
        plot.title = element_text(family = "Palatino", size=16))
```

```{r slopeGraphFictionByTypes}
# minimum number of votes to be included in the distribution, 
# see Rating FAQ: https://help.imdb.com/article/imdb/track-movies-tv/ratings-faq/G67Y87TFYYP6TWAV#calculatetop
ggplot(data = goodBadUgly, aes(x = rank, y = rating, group = type)) +
  geom_line(aes(color = type), size = 2, alpha = 0.9) +
  geom_point(aes(color = type, shape = type), size = 3, stroke=1, alpha = 0.9) +
  scale_x_discrete(position = "bottom") +
  scale_shape_manual(name = NULL, values = c(0,1,2,5)) +
  scale_color_tableau(name = NULL) +
  labs(
    title = imdb_title, subtitle = makeSubtitle(m, data), y = "rating",
    caption = "Source: https://www.imdb.com/interfaces/"
  ) +
  theme_pander(base_size = 16, base_family = "Courier") +
  theme(plot.margin = margin(10, 10, 10, 10),
        legend.position = "bottom",
        axis.title.x = element_blank(),
        axis.title.y = element_text(),
        plot.title = element_text(family = "Palatino", size=16))
```


```{r facetPercentilesByType}
ggplot(data = goodBadUgly, mapping = aes(rank, rating, fill=rank)) +
  geom_bar(stat = 'identity') +
  geom_line(aes(color = rank, group = 1), size = 1, alpha = 1) +
  geom_point(aes(color = rank, group = 1), size = 2, alpha = 1) +
  geom_text(aes(label = format(rating, digits=1)), nudge_y = 0.5, family = "Palatino", size = 6) +
  scale_fill_few(guide = guide_legend(nrow = 1, byrow = TRUE), name = NULL) +
  scale_color_few(guide = guide_legend(nrow = 1, byrow = TRUE), name = NULL) +
  facet_wrap(~type) +
  labs(x = NULL, y = NULL) +
  theme_pander(base_size = 16, base_family = "Parisine") +
  theme(legend.position = "none",
        axis.text.y = element_blank())
```

```{r slopeGraphFictionByPercentiles}
ggplot(data = goodBadUgly, aes(x = type, y = rating, group = rank)) +
  geom_line(aes(color = rank), size = 2, alpha = 1) +
  geom_point(aes(color = rank), size = 3, stroke=1, alpha = 1) +
  scale_x_discrete(position = "bottom") +
  scale_color_few(name = NULL, guide = guide_legend(nrow=1)) +
  labs(
    title = imdb_title, subtitle = makeSubtitle(m, data), y = "rating",
    caption = "Source: https://www.imdb.com/interfaces/"
  ) +
  theme_pander(base_size = 16, base_family = "Courier") +
  theme(plot.margin = margin(10, 10, 10, 10),
        axis.title.x = element_blank(),
        axis.title.y = element_text(),
        legend.position = "bottom",
        plot.title = element_text(family = "Palatino", size=16))
```


```{r slopeGraphDocumentary}
m = as.integer(25000/25)

data = movieratings[titleType2 %in% c("movie", "series") & numVotes > m]
tt = data.table(table(data$titleType, data$isGenreDocumentary, useNA = "ifany"))
setnames(tt, c('titleType', 'isDoc', 'count'))
tt[, isDoc := as.logical(isDoc)]

goodBadUglySlope = data.table(type=character(0), isDoc=logical(0), rank=character(0), rating=numeric(0))
for (i in seq(1, nrow(tt))) {
  type = tt[[i, 'titleType']]
  documentary = tt[[i, 'isDoc']]
  percentiles = quantile(data[titleType==type & isGenreDocumentary==documentary,]$averageRating,
                         probs=c(0.25, 0.5, 0.75, 0.9, 0.95, 0.99))
  goodBadUglySlope = rbind(goodBadUglySlope,
                           data.table(type=rep(type, length(percentiles)), 
                                      isDoc=rep(documentary, length(percentiles)),
                                      rank=names(percentiles), rating=percentiles))
}

goodBadUglySlope[, c("rank", "type", "isDoc") := list(
  factor(rank, levels = c("25%", "50%", "75%", "90%", "95%", "99%"), 
         labels = c("Bad\n25%", "Average\n50%", "Good\n75%", 
                    "Very Good\n90%", "Excellent\n95%", "Very Best\n99%"), 
         ordered = TRUE),
  factor(type, levels = c("movie", "tvMovie", "tvMiniSeries", "tvSeries"),
         labels = c("Movie", "TV Movie", "TV Mini Series", "TV Series"), 
         ordered = TRUE),
  factor(isDoc, levels = c(FALSE, TRUE), 
         labels = c("Fiction", "Doc"), ordered = TRUE))]

ggplot(data = goodBadUglySlope, aes(x = isDoc, y = rating, group=rank)) +
  geom_line(aes(color = rank), size = 2, alpha = 1) +
  geom_point(aes(color = rank), size = 3, alpha = 1) +
  facet_wrap(~type, nrow=1) +
  scale_x_discrete(position = "bottom") +
  scale_color_few(name = NULL, guide = guide_legend(nrow = 1)) +
  labs(
    title = "IMDb Rating Percentiles by Types: Fiction vs. Documentary",
    subtitle = makeSubtitle(m, data),
    caption = "Source: https://www.imdb.com/interfaces/",
    y = "rating"
  ) +
  theme_pander(base_size = 16, base_family = "Courier") +
  theme(plot.margin = margin(10, 10, 10, 10),
        axis.title.x = element_blank(),
        axis.title.y = element_text(),
        legend.position = "bottom",
        plot.title = element_text(family = "Palatino", size=16))
```


```{r worstIMDbMovies}
library(grid)
library(gridExtra)

m = 25000
data = movieratings[titleType %in% c("movie") & !isGenreDocumentary & !isAdult & numVotes > m]
# 
# https://help.imdb.com/article/imdb/track-movies-tv/ratings-faq/G67Y87TFYYP6TWAV?ref_=helpms_helpart_inline#
#
# weighted rating (WR) = (v ÷ (v+m)) × R + (m ÷ (v+m)) × C
# 
# Where:
# 
# R = average for the movie (mean) = (rating)
# 
# v = number of votes for the movie = (votes)
# 
# m = minimum votes required to be listed in the Top Rated list (currently 25,000)
# 
# C = the mean vote across the whole report
C = mean(data$averageRating)
data[, weightedRating := ((numVotes / (numVotes + m)) * averageRating + (m / (numVotes + m)) * C)]
setorder(data, weightedRating)
data[, c("Rank", "Rating", "Votes") := list(
  1:nrow(data), 
  round(weightedRating, digits = 1),
  format(numVotes, big.mark=","))]
setnames(data, c("primaryTitle", "startYear"), c("Title", "Year"))

pdf("graphics/imdb_worst_movies.pdf", height=14, width=11.5)
# pdf("graphics/imdb_worst_movies.pdf")
grid.table(data[1:50, c("Rank", "Title", "Year", "Rating", "Votes")],
           rows=NULL)
dev.off()
```

```{r earliestTitle}
firstYear = min(movieratings[startYear != '\\N',]$startYear, na.rm = TRUE)

firstMovieYear = min(movieratings[startYear != "\\N" & titleType == "movie",]$startYear, na.rm = TRUE)
```


```{r movieProductionByYear}
plotProductionOverTime <- function(data, type=NULL) {
  if (!is.null(type))
    data = data[titleType == type]
  else
    type = 'all films'
  min_year = min(data$startYear)
  ggplot(data[startYear <=  2020]) +
    geom_bar(aes(startYear, N),
             color = 'darkgray',
             fill = 'darkgray',
             stat = 'identity') +
    scale_x_continuous(breaks = c(min_year, 1920, 1940, 1960, 1980, 2000, 2020)) +
    labs(
      title = paste(tools::toTitleCase(type), "Production Over Time Since", min_year),
      subtitle = paste0("IMDb total titles produced annually for the type '", type, "'"),
      caption = "Source: https://www.imdb.com/interfaces/",
      y = NULL,
      x = NULL
    ) +
    theme_pander(base_size = 16, base_family = "Courier") +
    theme(
      plot.margin = margin(10, 10, 10, 10),
      plot.title = element_text(family = "Palatino", size = 16)
    )
}

data = movieratings[startYear != '\\N' & runtimeMinutes != '\\N',]
data = data[, c("startYear", 
                "runtimeMinutes") := list(
                  as.integer(startYear), 
                  as.integer(runtimeMinutes))][,
                                               .(N = .N, 
                                                 averageRatingMean = mean(averageRating),
                                                 averageRatingMax = max(averageRating),
                                                 numVotes = mean(numVotes),
                                                 runtimeMinutes=mean(runtimeMinutes)),
                                               by=.(titleType, startYear)]

plotProductionOverTime(data)
plotProductionOverTime(data, 'movie')
plotProductionOverTime(data, 'tvSeries')
```


```{r movieRuntimeByTypeAndYear}
data = movieratings[startYear != '\\N' & runtimeMinutes != '\\N' &
                      titleType %in% c('movie','short','tvMovie','series','tvMiniSeries','tvShort'),]
data = data[, c("startYear", 
                "runtimeMinutes") := list(
                  as.integer(startYear), 
                  as.integer(runtimeMinutes))][,
                                               .(N = .N, 
                                                 averageRatingMean = mean(averageRating),
                                                 averageRatingMax = max(averageRating),
                                                 numVotes = mean(numVotes),
                                                 runtimeHourMean=mean(runtimeMinutes/60.),
                                                 runtimeHourSum=sum(runtimeMinutes/60.)),
                                               by=.(titleType, startYear)]
min_year = min(data$startYear)
ggplot(data[startYear <=  2020 & titleType == 'movie']) +
  geom_bar(aes(startYear, runtimeHourSum), color='darkgray', fill='darkgray', stat = 'identity') +
  scale_x_continuous(breaks=c(min_year, 1920, 1940, 1960, 1980, 2000, 2020)) +
  #facet_wrap(~titleType, ncol = 1, scale = "free_y") +
  labs(
    title = "Movie Runtime Since 1894",
    subtitle = "IMDb title counts for type 'movie' and release year present",
    caption = "Source: https://www.imdb.com/interfaces/",
    y = NULL, x = NULL
  ) +
  theme_pander(base_size = 16, base_family = "Courier") +
  theme(plot.margin = margin(10, 10, 10, 10),
        plot.title = element_text(family = "Palatino"))
```

```{r moviesVsTVvsSeriesByYear}
movieratings[, titleType3 := ifelse(titleType %in% c('tvMiniSeries', 'tvSeries'), 'series', titleType)]
data = movieratings[titleType3 %in% c('movie', 'series', 'tvMovie') & startYear != '\\N',
                    .N, by=.(titleType3, startYear)][, startYear := as.integer(startYear)]
data = data[startYear >= 1970 & startYear <=  2020][, titleType := 
                                                      factor(titleType3, 
                                                             levels = c('movie','series','tvMovie'),
                                                             labels = c('Movies','TV (mini) series','TV movies'),
                                                             ordered = TRUE)]
setorder(data, titleType)

# Production over time
ggplot(data) +
  geom_bar(aes(startYear, N, fill=titleType), stat = 'identity', position = 'identity') +
  scale_fill_few(palette="Medium", name = NULL) +
  #scale_fill_economist(name = NULL) +
  scale_x_continuous(breaks=c(1970, 1980, 1990, 2000, 2010, 2020)) +
  labs(
    title = "Average Runtime over Time: Movies vs. TV Series vs. TV Movies",
    subtitle = "IMDb title counts by types since 1970, bars are not stacked",
    caption = "Source: https://www.imdb.com/interfaces/", 
    x=NULL, y=NULL) +
  theme_pander(base_size = 16, base_family = "Courier") +
  theme(plot.margin = margin(10, 10, 10, 10),
        legend.position = "bottom",
        plot.title = element_text(family = "Palatino"))

# Share of titles over time
ggplot(data) +
  geom_bar(aes(startYear, N, fill=titleType), stat = 'identity', position = 'fill') +
  scale_fill_few(palette="Medium", name = NULL) +
  #scale_fill_economist(name = NULL) +
  scale_y_continuous(label = percent) +
  scale_x_continuous(breaks=c(1970, 1980, 1990, 2000, 2010, 2020)) +
  labs(
    title = "Share over Time: Movies vs. TV Series vs. TV Movies",
    subtitle = "IMDb title counts by types since 1970",
    caption = "Source: https://www.imdb.com/interfaces/", 
    x=NULL, y=NULL) +
  theme_pander(base_size = 16, base_family = "Courier") +
  theme(plot.margin = margin(10, 10, 10, 10),
        legend.position = "bottom",
        plot.title = element_text(family = "Palatino"))
```
